version: '3.7'
services:
  app:
    build: .
   # 一旦コメントで対応
   # command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    ports:
      - "3000:80"
    volumes:
      - ".:/app:cached"
    depends_on:
      - db
    environment:
      DB_NAME: prototype_name_card
      DB_USER: root
      DB_HOST: db
      RAILS_ENV: development
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7.10
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3376:3306"
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
volumes:
  mysql-data:
  bundle:
